# Developing a computational psychiatry approach to social anxiety

\chaptermark{}

\noindent  _From this initial study, we aim to subsequently run two follow-up studies focusing on social anxiety, given its prevalence in modern society and relevance to social behaviour. In the first, we will identify the neurocomputational mechanisms underlying altered observational and experiential learning in social anxiety through model-based functional magnetic resonance imaging (fMRI) using the same social influence task. Then, partnering with Alena, a start-up developing digital mental health therapies, we will test the efficacy of smartphone-delivered psychotherapy in reducing behavioural symptoms in social anxiety disorder (SAD)._

## Uncovering the neurocomputational mechanisms underlying altered observational and experiential learning in social anxiety

### Background

Neuroimaging studies have robustly associated experiential learning with activity of brain regions implicated with reward processing and valuation, including ventromedial prefrontal cortex (vmPFC) representing individuals’ own valuation (Bartra et al., 2013) and the ventral striatum (VS)/nucleus accumbens (NAcc) encoding the RPE (O’Doherty et al., 2004) and signalling the rewarding value of potential outcomes (Brosch & Sander, 2013; Rangel et al., 2008; van der Meer & Redish, 2010). These regions also play a key role in social decision making (Ruff & Fehr, 2014), as humans assign intrinsic rewards to social actions (Cushman, 2024; Rilling & Sanfey, 2011). In social contexts however, an agent might additionally need to integrate information regarding other agent’s choices, and emotional states, comprehending the motives behind their actions and weighing the possible outcomes for those involved (Robson et al., 2020; Suzuki & O’Doherty, 2020). These ‘socially specific’ functions underlying observational learning are computed by the ‘social brain’, a network of brain regions consisting the anterior cingulate cortex (ACC), dorsomedial prefrontal cortex (dmPFC) and temporoparietal junction (TPJ) (Lockwood et al., 2020; Olsson et al., 2020). Ultimately, when making socially relevant decisions, both OL and EL processes are computed within the brain by an integrated hub consisting reward and socially relevant regions that track signals associated with direct experience (vmPFC) and vicarious valuation (ACC) with a combined reward/social prediction error represented in the striatum (NAcc/putamen) (Zhang & Gläscher, 2020).

The behavioural changes observed in social anxiety and social anxiety disorder (SAD) reflect alterations in brain function, primarily of regions associated with reward sensitivity, valuation, and social processing, with individuals with SAD robustly demonstrating reward network dysfunction in response to both monetary and social rewards (Becker et al., 2017; Cremers et al., 2015; Richey et al., 2014). Resting-state fMRI (rs-fMRI), further highlight changes in amygdala-frontal, parietal-frontal and amygdala-temporal connectivity (Mizzi et al., 2022, 2024), reflecting changes in emotion regulation (Jazaieri et al., 2014), self-referential processing (Whitfield-Gabrieli et al., 2011) and hypervigilance to social threats (Wong & Rapee, 2016). Changes in social behaviour reinforced through biased learning is similarly mediated by frontoparietal network (FPN) connectivity (Koban et al., 2023), implicated with modulating the top-down regulatory role of self-related content (Dixon & Gross, 2021). Heightened self-referential processing in SAD is also associated with increased connectivity from the left IPL and PCC to mPFC (Jamieson et al., 2023), (Davey et al., 2016; Davey & Harrison, 2022), a region implicated with self-representation within social contexts (D’Argembeau, 2013).

### Study Plan

Socially anxious individuals therefore demonstrate altered activity of prefrontal and striatal regions implicated with observational and experiential learning. We subsequently will use fMRI to uncover the neural components underlying differences in social decision-making driven by OL and EL observed in our initial study, by implementing the same social influence task on two cohorts, with high and low levels of social anxiety (SA) (n = 50 each). Performing perform group-level contrasts (high vs low SA), we expect to observe lowered activity and connectivity of prefrontal-striatal regions associated with monetary and social valuation during the trial outcome and choice preference reveal phases respectively, reflecting a lowered motivation for monetary/social reward. Furthermore, we predict increased activity and connectivity of prefrontal-striatal regions during both choice phases, as socially anxious individuals more strongly engage in self-referential processing when making social decisions. Finally, using model-based fMRI (Gläscher & O’Doherty, 2010), we expect for the model strategy (M6a) used by the high SA group to be strongly represented with lowered activity of the ventromedial prefrontal cortex (vmPFC) reflecting lowered confidence in the decision process (De Martino et al., 2013).

## Digital cognitive behavioural therapy reduces self-referencing in social anxiety disorder

### Background

Social anxiety disorder (SAD) is the third most common mental disorder behind substance use disorder and depression (Kessler et al., 2005), and the most common anxiety disorder, with a prevalence of approximately 10% (Kessler et al., 2005, 2012; Lecrubier et al., 2000). Individuals with SAD, for fear of being negatively judged by others, demonstrate a strong avoidance of social situations, adversely affecting functioning in social roles e.g., increased risk of dropping out of school, reduced workplace productivity, leading to high socioeconomic costs (Keller, 2003; Kessler, 2003). Social anxiety disorder is commonly treated using pharmacological and/or psychological approaches (Ströhle et al., 2018; Szuhany & Simon, 2022), which take effect in part by altering the processing of social information. Patient responsivity and improvement can therefore be inferred by measuring neural activity in response to specific behavioural paradigms. For example, both forms of treatment dampen the fear response, lowering activity of the amygdala to aversive social stimuli (Goldin et al., 2013; Klumpp et al., 2013), whilst improvements in emotion regulation as a result of cognitive-behavioural therapy (CBT) is associated with increased prefrontal and occipitotemporal activity (Brooks & Stein, 2022). Symptom reduction in SAD, following CBT, is similarly associated with reduced amygdalar-prefrontal (Yuan et al., 2016) and dorsolateral/dorsomedial prefrontal cortex (dl/dmPFC) activity (Goldin et al., 2021).

A theory-driven approach to psychiatry, generating formal accounts of mental health through computational models (Hauser et al., 2022; Hitchcock et al., 2022; Huys et al., 2016, 2021; Khaleghi et al., 2022), can further determine patient responsivity to treatment by providing an objective measure of the latent cognitive processes shaping brain activity and behaviour (Karvelis et al., 2023). This is particularly relevant for psychotherapy, as a neuro-computational approach can accurately characterise the behaviours and cognitions targeted by CBT (Reiter et al., 2021). Furthermore, as this approach is sensitive to both inter and intra-individual differences (Schaaf et al., 2023), model parameters represent ideal candidates for determining treatment efficacy and can be used in tandem with neuroimaging methods such as fMRI (Sohail & Zhang, 2024).

### Study Plan

Therefore, we aim in a second fMRI study to uncover the neurocomputational mechanisms underlying patient responsivity to a cognitive-behavioural therapy (CBT) program in SAD. Leveraging the recent trend in digital therapies, we will partner with Alena (Aya Technologies) a start-up specializing in digital mental health who have developed the Alena app, a self-guided CBT programme specifically designed to address social anxiety disorder. The programme is adapted from the Clark and Wells model of social anxiety (Clark & Wells, 1995) and follows a modular structure, each module targeting a core cognitive component contributing to the maintenance of social anxiety including negative beliefs, self-focused attention, post-event processing/rumination, and avoidance. Importantly, their program leverages a computational psychiatry approach, with gamified behavioural tasks providing objective measures of cognition. Mobile-based therapy further presents a number of advantages over conventional therapies (Gillan & Rutledge, 2021), including reduced waiting times, dense data phenotyping, increased patient retention, and the development of an individually tailored and manageable program. Furthermore, the absence of a face-to-face social interaction is pertinent to those with SAD as in-person treatments can be aversive. Ultimately, Alena’s digital CBT represents a safe, acceptable therapy, showing promising signs of rapid efficacy in the treatment of SAD (Garvert et al., 2023).

In our pre-post study, we aim to recruit forty individuals with a diagnosis of social anxiety disorder. Using fMRI, we will measure brain activity in response to the self-referential encoding task (SRET) (Derry & Kuiper, 1981), which assesses negative self-referential processing, a major component of the socially anxious phenotype (Talmon et al., 2021) and a behaviour targeted in CBT for SAD (Gregory & Peters, 2017). Participants after being scanned at baseline, will be randomly allocated to receive CBT-based therapy for social anxiety on the Alena app or to a wait list control group (n = 20 each). Participants randomised to the waitlist control group will subsequently be given access to the app for four weeks after the study is concluded. Comparing brain activity at both timepoints (post vs pre), we expect to observe reduced activity of prefrontal regions implicated in self-referencing and rumination among participants assigned to receive treatment in the app, whilst no changes are expected amongst the control group.

The study will ultimately provide novel scientific evidence for the efficacy underlying a smartphone-based approach in delivering CBT, furthering the development of digital therapies.
