\backmatter
# References {-}

\chaptermark{}

\setlength{\parindent}{0pt}
\setlength{\leftskip}{0em}
\setlength{\parskip}{1em}

Abraham, A., & Hermann, C. (2015). Biases in probabilistic category learning in relation to social anxiety. Frontiers in Psychology, 6.

Admon, R., & Pizzagalli, D. A. (2015). Dysfunctional reward processing in depression. Current Opinion in Psychology, 4, 114–118.

Aylward, J., Valton, V., Ahn, W.-Y., Bond, R. L., Dayan, P., Roiser, J. P., & Robinson, O. J. (2019). Altered learning under uncertainty in unmedicated mood and anxiety disorders. Nature Human Behaviour, 3(10), 1116–1123.

Balietti, S. (2017). nodeGame: Real-time, synchronous, online experiments in the browser. Behavior Research Methods, 49(5), 1696–1715.

Bartra, O., McGuire, J. T., & Kable, J. W. (2013). The valuation system: A coordinate-based meta-analysis of BOLD fMRI experiments examining neural correlates of subjective value. NeuroImage, 76, 412–427.

Becker, M. P. I., Simon, D., Miltner, W. H. R., & Straube, T. (2017). Altered activation of the ventral striatum under performance-related observation in social anxiety disorder. Psychological Medicine, 47(14), 2502–2512.

Becker, M. P. I., Voegler, R., Peterburs, J., Hofmann, D., Bellebaum, C., & Straube, T. (2019). Reward Prediction Error Signaling during Reinforcement Learning in Social Anxiety Disorder is altered by Social Observation (p. 821512). bioRxiv.

Beltzer, M. L., Adams, S., Beling, P. A., & Teachman, B. A. (2019). Social Anxiety and Dynamic Social Reinforcement Learning in a Volatile Environment. Clinical Psychological Science, 7(6), 1372–1388.

Beltzer, M. L., Daniel, K. E., Daros, A. R., & Teachman, B. A. (2023). Examining social reinforcement learning in social anxiety. Journal of Behavior Therapy and Experimental Psychiatry, 80, 101810.

Bică, A., Crețu, R. Z., & Podina, I. R. (2021). Money Versus Social Rank: An Empirical Investigation of Unfairness in Social Anxiety. Cognitive Therapy and Research, 45(4), 642–651.

Bishop, S. J. (2007). Neurocognitive mechanisms of anxiety: An integrative account. Trends in Cognitive Sciences, 11(7), 307–316.

Brooks, S. J., & Stein, D. J. (2015). A systematic review of the neural bases of psychotherapy for anxiety and related disorders. Dialogues in Clinical Neuroscience, 17(3), 261–279.

Brosch, T., & Sander, D. (2013). Neurocognitive mechanisms underlying value-based decision-making: From core values to economic value. Frontiers in Human Neuroscience, 7.

Browning, M., Behrens, T. E., Jocham, G., O'Reilly, J. X., & Bishop, S. J. (2015). Anxious individuals have difficulty learning the causal statistics of aversive environments. Nature Neuroscience, 18(4), 590–596.

Burke, C. J., Tobler, P. N., Baddeley, M., & Schultz, W. (2010). Neural mechanisms of observational learning. Proceedings of the National Academy of Sciences, 107(32), 14431–14436.

Button, K. S., Browning, M., Munafò, M. R., & Lewis, G. (2012). Social inference and social anxiety: Evidence of a fear-congruent self-referential learning bias. Journal of Behavior Therapy and Experimental Psychiatry, 43(4), 1082–1087.

Campbell-Meiklejohn, D., Simonsen, A., Frith, C. D., & Daw, N. D. (2017). Independent Neural Computation of Value from Other People's Confidence. Journal of Neuroscience, 37(3), 673–684.

Carleton, R. N., Collimore, K. C., McCabe, R. E., & Antony, M. M. (2011). Addressing revisions to the Brief Fear of Negative Evaluation scale: Measuring fear of negative evaluation across anxiety and mood disorders. Journal of Anxiety Disorders, 25(6), 822–828.

Cattell, R. B. (1966). The Scree Test For The Number Of Factors. Multivariate Behavioral Research, 1(2), 245–276.

Chandler, J., Mueller, P., & Paolacci, G. (2014). Nonnaïveté among Amazon Mechanical Turk workers: Consequences and solutions for behavioral researchers. Behavior Research Methods, 46(1), 112–130.

Charpentier, C. J., Wu, Q., Min, S., Ding, W., Cockburn, J., & O'Doherty, J. P. (2023). Heterogeneity in strategy use during arbitration between experiential and observational learning. OSF.

Chen, D. L., Schonger, M., & Wickens, C. (2016). oTree—An open-source platform for laboratory, online, and field experiments. Journal of Behavioral and Experimental Finance, 9, 88–97.

Cremers, H. R., Veer, I. M., Spinhoven, P., Rombouts, S. A. R. B., & Roelofs, K. (2015). Neural sensitivity to social reward and punishment anticipation in social anxiety disorder. Frontiers in Behavioral Neuroscience, 8.

Cushman, F. (2024). Computational Social Psychology. Annual Review of Psychology, 75(Volume 75, 2024), 625–652.

D'Argembeau, A. (2013). On the Role of the Ventromedial Prefrontal Cortex in Self-Processing: The Valuation Hypothesis. Frontiers in Human Neuroscience, 7.

Davey, C. G., Pujol, J., & Harrison, B. J. (2016). Mapping the self in the brain's default mode network. NeuroImage, 132, 390–397.

Davey, C. G., & Harrison, B. J. (2022). The self on its axis: A framework for understanding depression. Translational Psychiatry, 12(1), 1–9.

De Martino, B., Fleming, S. M., Garrett, N., & Dolan, R. J. (2013). Confidence in value-based choice. Nature Neuroscience, 16(1), 105–110.

Declerck, C. H., Boone, C., & Emonds, G. (2013). When do people cooperate? The neuroeconomics of prosocial decision making. Brain and Cognition, 81(1), 95–117.

Derry, P. A., & Kuiper, N. A. (1981). Schematic processing and self-reference in clinical depression. Journal of Abnormal Psychology, 90(4), 286–297.

Dixon, M. L., & Gross, J. J. (2021). Dynamic network organization of the self: Implications for affective experience. Current Opinion in Behavioral Sciences, 39, 1–9.

Dunne, S., & O'Doherty, J. P. (2013). Insights from the application of computational neuroimaging to social neuroscience. Current Opinion in Neurobiology, 23(3), 387–392.

Eshel, N., & Roiser, J. P. (2010). Reward and Punishment Processing in Depression. Biological Psychiatry, 68(2), 118–124.

Fatima, M., & Ghayas, S. (2017). Relationship between Self-Esteem and Social Anxiety: Role of Social Connectedness as a Mediator (world).

Feczko, E., Miranda-Dominguez, O., Marr, M., Graham, A. M., Nigg, J. T., & Fair, D. A. (2019). The Heterogeneity Problem: Approaches to Identify Psychiatric Subtypes. Trends in Cognitive Sciences, 23(7), 584–601.

Feng, C., Cao, J., Li, Y., Wu, H., & Mobbs, D. (2018). The pursuit of social acceptance: Aberrant conformity in social anxiety disorder. Social Cognitive and Affective Neuroscience, 13(8), 809–817.

Foa, E. B., Huppert, J. D., Leiberg, S., Langner, R., Kichic, R., Hajcak, G., & Salkovskis, P. M. (2002). The Obsessive-Compulsive Inventory: Development and validation of a short version. Psychological Assessment, 14(4), 485–496.

Fox, M. D., & Greicius, M. (2010). Clinical applications of resting state functional connectivity. Frontiers in Systems Neuroscience, 4.

Franken, I. H. A., van Strien, J. W., Nijs, I., & Muris, P. (2008). Impulsivity is associated with behavioral decision-making deficits. Psychiatry Research, 158(2), 155–163.

Fried, E. (2017). Moving forward: How depression heterogeneity hinders progress in treatment and research. Expert Review of Neurotherapeutics, 17(5), 423–425.

Garner, D. M., Olmsted, M. P., Bohr, Y., & Garfinkel, P. E. (1982). The Eating Attitudes Test: Psychometric features and clinical correlates. Psychological Medicine, 12(4), 871–878.

Garvert, M. M., Linke, S., McCloud, T., Meyer, S. S., Sobanska, S., Long, A., Huys, Q. J. M., & Ahmadi, M. (2023). The Safety, Acceptability and Efficacy of Alena, a Modularized CBT-based Mobile App Intervention for Social Anxiety: A Randomised Controlled Trial (p. 2023.05.30.23288513). medRxiv.

Giamattei, M., Yahosseini, K. S., Gächter, S., & Molleman, L. (2020). LIONESS Lab: A free web-based platform for conducting interactive experiments online. Journal of the Economic Science Association, 6(1), 95–111.

Gilboa-Schechtman, E., Keshet, H., Livne, T., Berger, U., Zabag, R., Hermesh, H., & Marom, S. (2017). Explicit and implicit self-evaluations in social anxiety disorder. Journal of Abnormal Psychology, 126(3), 285–290.

Gillan, C. M., Kosinski, M., Whelan, R., Phelps, E. A., & Daw, N. D. (2016). Characterizing a psychiatric symptom dimension related to deficits in goal-directed control. eLife, 5, e11305.

Gillan, C. M., & Seow, T. X. F. (2020). Carving Out New Transdiagnostic Dimensions for Research in Mental Health. Biological Psychiatry: Cognitive Neuroscience and Neuroimaging, 5(10), 932–934.

Gillan, C. M., & Rutledge, R. B. (2021). Smartphones and the Neuroscience of Mental Health. Annual Review of Neuroscience, 44(Volume 44, 2021), 129–151.

Gläscher, J. P., & O'Doherty, J. P. (2010). Model-based approaches to neuroimaging: Combining reinforcement learning theory with fMRI data. WIREs Cognitive Science, 1(4), 501–510.

Glimcher, P. W. (2013). Neuroeconomics: Decision Making and the Brain. Academic Press.

Goldin, P. R., Ziv, M., Jazaieri, H., Hahn, K., Heimberg, R., & Gross, J. J. (2013). Impact of Cognitive Behavioral Therapy for Social Anxiety Disorder on the Neural Dynamics of Cognitive Reappraisal of Negative Self-beliefs: Randomized Clinical Trial. JAMA Psychiatry, 70(10), 1048–1056.

Goldin, P. R., Thurston, M., Allende, S., Moodie, C., Dixon, M. L., Heimberg, R. G., & Gross, J. J. (2021). Evaluation of Cognitive Behavioral Therapy vs Mindfulness Meditation in Brain Changes During Reappraisal and Acceptance Among Patients With Social Anxiety Disorder: A Randomized Clinical Trial. JAMA Psychiatry, 78(10), 1134–1142.

Gorsuch, R. L. (2014). Factor Analysis: Classic Edition (2nd ed.). Routledge.

Gregory, B., & Peters, L. (2017). Changes in the self during cognitive behavioural therapy for social anxiety disorder: A systematic review. Clinical Psychology Review, 52, 1–18.

Hasler, G. (2012). Can the neuroeconomics revolution revolutionize psychiatry? Neuroscience & Biobehavioral Reviews, 36(1), 64–78.

Hauser, T. U., Skvortsova, V., Choudhury, M. D., & Koutsouleris, N. (2022). The promise of a model-based psychiatry: Building computational models of mental ill health. The Lancet Digital Health, 4(11), e816–e828.

Hitchcock, P. F., Fried, E. I., & Frank, M. J. (2022). Computational Psychiatry Needs Time and Context. Annual Review of Psychology, 73(Volume 73, 2022), 243–270.

Hofheinz, C., Germar, M., Schultze, T., Michalak, J., & Mojzisch, A. (2017). Are Depressed People More or Less Susceptible to Informational Social Influence? Cognitive Therapy and Research, 41(5), 699–711.

Hopkins, A. K., Gillan, C., Roiser, J., Wise, T., & Sidarus, N. (2022). Optimising the measurement of anxious-depressive, compulsivity and intrusive thought and social withdrawal transdiagnostic symptom dimensions. OSF.

Hoven, M., Luigjes, J., Denys, D., Rouault, M., & van Holst, R. J. (2023). How do confidence and self-beliefs relate in psychopathology: A transdiagnostic approach. Nature Mental Health, 1(5), 337–345.

Huys, Q. J. M., Maia, T. V., & Frank, M. J. (2016). Computational psychiatry as a bridge from neuroscience to clinical applications. Nature Neuroscience, 19(3), 404–413.

Huys, Q. J. M., Browning, M., Paulus, M. P., & Frank, M. J. (2021). Advances in the computational understanding of mental illness. Neuropsychopharmacology, 46(1), 3–19.

Jamieson, A. J., Harrison, B. J., Delahoy, R., Schmaal, L., Felmingham, K. L., Phillips, L., & Davey, C. G. (2023). A brain model of altered self-appraisal in social anxiety disorder. Translational Psychiatry, 13(1), 1–9.

Jazaieri, H., Morrison, A. S., Goldin, P. R., & Gross, J. J. (2014). The Role of Emotion and Emotion Regulation in Social Anxiety Disorder. Current Psychiatry Reports, 17(1), 531.

Joiner, J., Piva, M., Turrin, C., & Chang, S. W. C. (2017). Social learning through prediction error in the brain. Npj Science of Learning, 2(1), Article 1.

Keller, M. B. (2003). The lifelong course of social anxiety disorder: A clinical perspective. Acta Psychiatrica Scandinavica, 108(s417), 85–94.

Kessler, R. C. (2003). The impairments caused by social phobia in the general population: Implications for intervention. Acta Psychiatrica Scandinavica, 108(s417), 19–27.

Kessler, R. C., Berglund, P., Demler, O., Jin, R., Merikangas, K. R., & Walters, E. E. (2005). Lifetime Prevalence and Age-of-Onset Distributions of DSM-IV Disorders in the National Comorbidity Survey Replication. Archives of General Psychiatry, 62(6), 593–602.

Kessler, R. C., Petukhova, M., Sampson, N. A., Zaslavsky, A. M., & Wittchen, H.-U. (2012). Twelve-month and lifetime prevalence and lifetime morbid risk of anxiety and mood disorders in the United States. International Journal of Methods in Psychiatric Research, 21(3), 169–184.

Khaleghi, A., Mohammadi, M. R., Shahi, K., & Nasrabadi, A. M. (2022). Computational Neuroscience Approach to Psychiatry: A Review on Theory-driven Approaches. Clinical Psychopharmacology and Neuroscience, 20(1), 26–36.

Kim, S., & Lee, D. (2011). Prefrontal Cortex and Impulsive Decision Making. Biological Psychiatry, 69(12), 1140–1146.
Kishida, K. T., King-Casas, B., & Montague, P. R. (2010). Neuroeconomic approaches to mental disorders. Neuron, 67(4), 543–554.

Klumpp, H., Fitzgerald, D. A., & Phan, K. L. (2013). Neural predictors and mechanisms of cognitive behavioral therapy on threat processing in social anxiety disorder. Progress in Neuro-Psychopharmacology and Biological Psychiatry, 45, 83–91.

Koban, L., Schneider, R., Ashar, Y. K., Andrews-Hanna, J. R., Landy, L., Moscovitch, D. A., Wager, T. D., & Arch, J. J. (2017). Social anxiety is characterized by biased learning about performance and the self. Emotion (Washington, D.C.), 17(8), 1144–1155.

Koban, L., Andrews-Hanna, J. R., Ives, L., Wager, T. D., & Arch, J. J. (2023). Brain mediators of biased social learning of self-perception in social anxiety disorder. Translational Psychiatry, 13(1), 1–9.

Leary, M. R., Kowalski, R. M., & Campbell, C. D. (1988). Self-presentational concerns and social anxiety: The role of generalized impression expectancies. Journal of Research in Personality, 22(3), 308–321.

Lecrubier, Y., Wittchen, H. U., Faravelli, C., Bobes, J., Patel, A., & Knapp, M. (2000). A European perspective on social anxiety disorder. European Psychiatry, 15(1), 5–16.

Lee, D., Seo, H., & Jung, M. W. (2012). Neural Basis of Reinforcement Learning and Decision Making. Annual Review of Neuroscience, 35(1), 287–308.

Lee, H., & Chung, D. (2022). Characterization of the Core Determinants of Social Influence From a Computational and Cognitive Perspective. Frontiers in Psychiatry, 13.

Liebowitz, M. R. (1987). Social Phobia.

Lockwood, P. L., Apps, M. A. J., & Chang, S. W. C. (2020). Is There a 'Social' Brain? Implementations and Algorithms. Trends in Cognitive Sciences, 24(10), 802–813.

Lockwood, P. L., & Klein-Flügge, M. C. (2021). Computational modelling of social cognition and behaviour—A reinforcement learning primer. Social Cognitive and Affective Neuroscience, 16(8), 761–771.

Loewenstein, G., Rick, S., & Cohen, J. D. (2008). Neuroeconomics. Annual Review of Psychology, 59(Volume 59, 2008), 647–672.

Maia, T. V., & Frank, M. J. (2011). From reinforcement learning models to psychiatric and neurological disorders. Nature Neuroscience, 14(2), 154–162.

Marin, R. S., Biedrzycki, R. C., & Firinciogullari, S. (1991). Reliability and validity of the apathy evaluation scale. Psychiatry Research, 38(2), 143–162.

Mizzi, S., Pedersen, M., Lorenzetti, V., Heinrichs, M., & Labuschagne, I. (2022). Resting-state neuroimaging in social anxiety disorder: A systematic review. Molecular Psychiatry, 27(1), 164–179.

Mizzi, S., Pedersen, M., Rossell, S. L., Rendell, P., Terrett, G., Heinrichs, M., & Labuschagne, I. (2024). Resting-state amygdala subregion and precuneus connectivity provide evidence for a dimensional approach to studying social anxiety disorder. Translational Psychiatry, 14(1), 1–10.

O'Doherty, J., Dayan, P., Schultz, J., Deichmann, R., Friston, K., & Dolan, R. J. (2004). Dissociable Roles of Ventral and Dorsal Striatum in Instrumental Conditioning. Science, 304(5669), 452–454.

O'Doherty, J. P., Cockburn, J., & Pauli, W. M. (2017). Learning, Reward, and Decision Making. Annual Review of Psychology, 68(1), 73–100.

O'Doherty, J. P., Lee, S. W., Tadayonnejad, R., Cockburn, J., Iigaya, K., & Charpentier, C. J. (2021). Why and how the brain weights contributions from a mixture of experts. Neuroscience & Biobehavioral Reviews, 123, 14–23.

Olsson, A., Knapska, E., & Lindström, B. (2020). The neural and computational systems of social learning. Nature Reviews Neuroscience, 21(4), Article 4.

Pärnamets, P., & Olsson, A. (2020). Integration of social cues and individual experiences during instrumental avoidance learning. PLOS Computational Biology, 16(9), e1008163.

Patton, J. H., Stanford, M. S., & Barratt, E. S. (1995). Factor structure of the barratt impulsiveness scale. Journal of Clinical Psychology, 51(6), 768–774.

Peterburs, J., Albrecht, C., & Bellebaum, C. (2022). The impact of social anxiety on feedback-based go and nogo learning. Psychological Research, 86(1), 110–124.

Pike, A. C., & Robinson, O. J. (2022). Reinforcement Learning in Patients With Mood and Anxiety Disorders vs Control Individuals: A Systematic Review and Meta-analysis. JAMA Psychiatry, 79(4), 313–322.

Piray, P., Ly, V., Roelofs, K., Cools, R., & Toni, I. (2019). Emotionally Aversive Cues Suppress Neural Systems Underlying Optimal Learning in Socially Anxious Individuals. Journal of Neuroscience, 39(8), 1445–1456.

Rangel, A., Camerer, C., & Montague, P. R. (2008). A framework for studying the neurobiology of value-based decision making. Nature Reviews Neuroscience, 9(7), 545–556.

Rangel, A. (2009). Chapter 28—The Computation and Comparison of Value in Goal-directed Choice. In P. W. Glimcher, C. F. Camerer, E. Fehr, & R. A. Poldrack (Eds.), Neuroeconomics (pp. 425–440). Academic Press.

Rangel, A., & Hare, T. (2010). Neural computations associated with goal-directed choice. Current Opinion in Neurobiology, 20(2), 262–270.

Read Montague, P. (2018). Chapter 11—Computational Phenotypes Revealed by Interactive Economic Games. In A. Anticevic & J. D. Murray (Eds.), Computational Psychiatry (pp. 273–292). Academic Press.

Reiter, A. M., Atiya, N. A., Berwian, I. M., & Huys, Q. J. (2021). Neuro-cognitive processes as mediators of psychological treatment effects. Current Opinion in Behavioral Sciences, 38, 103–109.

Richey, J. A., Rittenberg, A., Hughes, L., Damiano, C. R., Sabatino, A., Miller, S., Hanna, E., Bodfish, J. W., & Dichter, G. S. (2014). Common and distinct neural features of social and non-social reward processing in autism and social anxiety disorder. Social Cognitive and Affective Neuroscience, 9(3), 367–377.

Rilling, J. K., & Sanfey, A. G. (2011). The Neuroscience of Social Decision-Making. Annual Review of Psychology, 62(Volume 62, 2011), 23–48.

Robbins, T. W., Gillan, C. M., Smith, D. G., Wit, S. de, & Ersche, K. D. (2012). Neurocognitive endophenotypes of impulsivity and compulsivity: Towards dimensional psychiatry. Trends in Cognitive Sciences, 16(1), 81–91.

Robson, S. E., Repetto, L., Gountouna, V.-E., & Nicodemus, K. K. (2020). A review of neuroeconomic gameplay in psychiatric disorders. Molecular Psychiatry, 25(1), 67–81.

Rouault, M., Seow, T., Gillan, C. M., & Fleming, S. M. (2018). Psychiatric Symptom Dimensions Are Associated With Dissociable Shifts in Metacognition but Not Task Performance. Biological Psychiatry, 84(6), 443–451.

Ruff, C. C., & Fehr, E. (2014). The neurobiology of rewards and values in social decision making. Nature Reviews Neuroscience, 15(8), 549–562.

Schaaf, J. V., Weidinger, L., Molleman, L., & van den Bos, W. (2023). Test–retest reliability of reinforcement learning parameters. Behavior Research Methods.

Seema, G. B., & Kumar, G. V. (2017). Self-Esteem and Social Anxiety in Adolescent Students. Journal of Psychosocial Research, 12(2), 247–254.

Seow, T. X. F., & Gillan, C. M. (2020). Transdiagnostic Phenotyping Reveals a Host of Metacognitive Deficits Implicated in Compulsivity. Scientific Reports, 10(1), 2883.

Serra, D. (2021). Decision-making: From neuroscience to neuroeconomics—an overview. Theory and Decision, 91(1), 1–80.
Spielberger, C. D. (1970). Manual for the State-Trait Anxiety Inventory (Self-evaluation Questionnaire). (No Title).

Spokas, M. E., & Cardaciotto, L. (2014). Heterogeneity Within Social Anxiety Disorder. In The Wiley Blackwell Handbook of Social Anxiety Disorder (pp. 247–267). John Wiley & Sons, Ltd.

Ströhle, A., Gensichen, J., & Domschke, K. (2018). The Diagnosis and Treatment of Anxiety Disorders. Deutsches Arzteblatt International, 155(37), 611–620.

Sutton, R. S., & Barto, A. G. (2018). Reinforcement Learning, second edition: An Introduction. MIT Press.

Suzuki, S., & O'Doherty, J. P. (2020). Breaking human social decision making into multiple components and then putting them together again. Cortex, 127, 221–230.

Szuhany, K. L., & Simon, N. M. (2022). Anxiety Disorders: A Review. JAMA, 328(24), 2431–2445.

Talmon, A., Dixon, M. L., Goldin, P. R., Heimberg, R. G., & Gross, J. J. (2021). Neurocognitive Heterogeneity in Social Anxiety Disorder: The Role of Self-Referential Processing and Childhood Maltreatment. Clinical Psychological Science, 9(6), 1045–1058.

Tomlin, D., Nedic, A., Prentice, D. A., Holmes, P., & Cohen, J. D. (2013). The Neural Substrates of Social Influence on Decision Making. PLOS ONE, 8(1), e52630.

Trudel, N., Lockwood, P. L., Rushworth, M. F., & Wittmann, M. K. (2023). Neural activity tracking identity and confidence in social information. eLife, 12, e71315.

Vaghi, M. M., Luyckx, F., Sule, A., Fineberg, N. A., Robbins, T. W., & De Martino, B. (2017). Compulsivity Reveals a Novel Dissociation between Action and Confidence. Neuron, 96(2), 348-354.e4.

Van Der Meer, M. A. A., & Redish, A. D. (2010). Expectancies in decision making, reinforcement learning, and ventral striatum. Frontiers in Neuroscience, 3.

Voegler, R., Peterburs, J., Bellebaum, C., & Straube, T. (2019). Modulation of feedback processing by social context in social anxiety disorder (SAD)–an event-related potentials (ERPs) study. Scientific Reports, 9(1), 4795.

Wechsler, D. (2019). Wechsler Adult Intelligence Scale—Third Edition [dataset].

Wells, A., Clark, D. M., Salkovskis, P., Ludgate, J., Hackmann, A., & Gelder, M. (1995). Social phobia: The role of in-situation safety behaviors in maintaining anxiety and negative beliefs. Behavior Therapy, 26(1), 153–161.

Whitfield-Gabrieli, S., Moran, J. M., Nieto-Castañón, A., Triantafyllou, C., Saxe, R., & Gabrieli, J. D. E. (2011). Associations and dissociations between default and self-reference networks in the human brain. NeuroImage, 55(1), 225–232.

Wong, Q. J. J., & Rapee, R. M. (2016). The aetiology and maintenance of social anxiety disorder: A synthesis of complementary theoretical models and formulation of a new integrated model. Journal of Affective Disorders, 203, 84–100.

Zabag, R., Gilboa-Schechtman, E., & Levy-Gigi, E. (2022). Reacting to changing environment: Updating patterns in social anxiety. Behaviour Research and Therapy, 157, 104159.

Zabag, R., Azoulay, R., Rinck, M., Becker, E., Levy-Gigi, E., & Gilboa-Schechtman, E. (2023). You never get a chance to undo a negative first impression: Social anxiety is associated with impaired positive updating of social information. Personality and Individual Differences, 203, 111993.

Zhang, L., & Gläscher, J. (2020). A brain network supporting social influences in human decision-making. Science Advances, 6(34), eabb4159.

Zung, W. W. K. (1965). A Self-Rating Depression Scale. Archives of General Psychiatry, 12(1), 63–70.