#!/bin/bash

# Install TinyTeX
R -e "install.packages('tinytex', repos='https://cloud.r-project.org/')"
R -e "tinytex::install_tinytex(force = TRUE)"
R -e "tinytex::tlmgr_install(c('lm-math', 'pdftex', 'xetex', 'luatex'))"
R -e "tinytex::tlmgr_update()"

# Set the necessary environment variables for TinyTeX
echo "export PATH=\"/usr/local/texlive/bin/x86_64-linux:\${PATH}\"" >> ${HOME}/.bashrc
echo "export PATH=\"${HOME}/.TinyTeX/bin/x86_64-linux:\${PATH}\"" >> ${HOME}/.bashrc