name: Publish Thesis HTML

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  render-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.5.0

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Change working directory
      run: cd ${{ github.workspace }}

    - name: Install Dependencies
      run: |
        sudo apt-get install -y pandoc pandoc-citeproc
        Rscript -e "install.packages(c('bookdown', 'tinytex'))"
        Rscript -e "tinytex::install_tinytex()"

    - name: Render Book
      run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: _book/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: render-book

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.5.0

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: book

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: '_book'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
