name: Publish Thesis HTML

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            libxml2-dev \
            libcairo2-dev \
            libgit2-dev \
            libglpk40 \
            libglu1-mesa-dev \
            libgmp3-dev \
            libgsl0-dev \
            libhdf5-dev \
            libmpfr-dev \
            libssl-dev \
            libv8-dev \
            libzmq3-dev \
            pandoc \
            pandoc-citeproc \
            wget \
            unzip \
            gcc \
            make \
            libc-dev \
            texlive-fonts-extra

      - name: Set timezone
        run: |
          ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime
          echo "Europe/London" > /etc/timezone

      - name: Install TinyTeX
        run: |
          R -e "install.packages('tinytex', repos='https://cloud.r-project.org/')"
          R -e "tinytex::install_tinytex(force = TRUE)"
          R -e "tinytex::tlmgr_install(c('lm-math', 'pdftex', 'xetex', 'luatex'))"
          R -e "tinytex::tlmgr_update()"

      - name: Set TinyTeX environment variables
        run: |
          echo "PATH=/usr/local/texlive/bin/x86_64-linux:$PATH" >> $GITHUB_ENV
          echo "PATH=/home/runner/.TinyTeX/bin/x86_64-linux:$PATH" >> $GITHUB_ENV

      - name: Install R packages
        run: |
          R -e "install.packages(c('ggsignif', 'gridExtra', 'plan', 'remotes'), repos='https://cloud.r-project.org/')"
          R -e "remotes::install_github('lcreteig/amsterdown')"

      - name: Render thesis to HTML
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_file = "thesis.html")'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          destination: ./

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
