name: Render and Deploy Book

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install Dependencies
      run: |
        sudo apt-get install -y pandoc pandoc-citeproc
        Rscript -e "install.packages(c('bookdown', 'tinytex'))"
        Rscript -e "tinytex::install_tinytex()"

    - name: Render Book
      run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        publish_branch: gh-pages
